import { test, expect } from '@playwright/test'

test('browse, mutate, download and receive real events', async ({ page, request }, info) => {
  const folder = `Folder-${info.project.name}`
  const renamed = `Renamed-${info.project.name}`
  await page.goto('/')
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
  await expect(page.getByText('hello.txt', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Documents', exact: true }).click()
  await expect(page.getByText('No files to show')).toBeVisible()
  await page.getByRole('button', { name: 'Shared folder', exact: true }).click()
  await page.getByRole('button', { name: 'Grid view', exact: true }).click()
  await expect(page.locator('.file-grid')).toBeVisible()
  await page.getByRole('button', { name: 'List view', exact: true }).click()
  await page.getByLabel('Search files').fill('hello')
  await expect(page.getByRole('button', { name: 'Documents', exact: true })).toHaveCount(0)
  await page.getByLabel('Search files').fill('')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download hello.txt', exact: true }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('hello.txt')
  const stream = await download.createReadStream()
  let data = ''; for await (const chunk of stream!) data += chunk.toString()
  expect(data).toBe('Real shared file\n')
  await page.getByRole('button', { name: /Create folder/ }).click()
  await page.getByLabel('Name', { exact: true }).fill(folder)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('button', { name: folder, exact: true })).toBeVisible()
  await page.getByRole('button', { name: `Actions for ${folder}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill(renamed)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('button', { name: renamed, exact: true })).toBeVisible()
  const live = `Live-${info.project.name}`
  const response = await request.post('/api/v1/directories', { headers: { 'X-SplitShare-Request': '1' }, data: { parent: '/', name: live } })
  expect(response.status()).toBe(201)
  await expect(page.getByRole('button', { name: live, exact: true })).toBeVisible()
  await page.getByRole('button', { name: `Actions for ${renamed}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete', exact: true }).click()
  await page.getByLabel('Confirm deletion').fill(renamed)
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('button', { name: renamed, exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${info.project.name}.png`, fullPage: true })
})

test('uploads, drag/drop, file/image/text paste and conflict resolution', async ({ page, request }, info) => {
  const suffix = info.project.name
  await page.goto('/')
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
  await page.locator('input[type=file]').setInputFiles([
    { name: `upload-a-${suffix}.txt`, mimeType: 'text/plain', buffer: Buffer.from('alpha') },
    { name: `upload-b-${suffix}.txt`, mimeType: 'text/plain', buffer: Buffer.from('beta') },
  ])
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`upload-a-${suffix}.txt`, { exact: true })).toBeVisible()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`upload-b-${suffix}.txt`, { exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: 'Aggregate upload progress' })).toHaveAttribute('value','100')
  await page.locator('main').evaluate((element,suffix) => {
    const data = new DataTransfer(); data.items.add(new File(['dropped'],`drop-${suffix}.txt`,{ type:'text/plain' }))
    element.dispatchEvent(new DragEvent('drop',{ bubbles:true, cancelable:true, dataTransfer:data }))
  },suffix)
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`drop-${suffix}.txt`, { exact: true })).toBeVisible()
  await page.locator('main').evaluate((element,suffix) => {
    const data = new DataTransfer(); data.items.add(new File(['pasted file'],`paste-${suffix}.txt`,{type:'text/plain'}))
    // Firefox discards constructor-supplied clipboardData on synthetic events.
    const event = new ClipboardEvent('paste',{bubbles:true,cancelable:true})
    Object.defineProperty(event,'clipboardData',{value:data})
    element.dispatchEvent(event)
  },suffix)
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`paste-${suffix}.txt`, { exact: true })).toBeVisible()
  await page.locator('main').evaluate(element => {
    const data = new DataTransfer(); data.setData('text/plain','Draft from clipboard')
    // Firefox discards constructor-supplied clipboardData on synthetic events.
    const event = new ClipboardEvent('paste',{bubbles:true,cancelable:true})
    Object.defineProperty(event,'clipboardData',{value:data})
    element.dispatchEvent(event)
  })
  await expect(page.getByRole('heading', {name:'Save clipboard text'})).toBeVisible()
  await page.getByLabel('Filename',{exact:true}).fill(`draft-${suffix}.txt`)
  expect((await request.get(`/api/v1/files/download?path=/draft-${suffix}.txt`)).status()).toBe(404)
  await page.getByRole('button',{name:'Save file',exact:true}).click()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`draft-${suffix}.txt`,{exact:true})).toBeVisible()
  expect(await (await request.get(`/api/v1/files/download?path=/draft-${suffix}.txt`)).text()).toBe('Draft from clipboard')
  await page.locator('main').evaluate(element => {
    const bytes = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aSuoAAAAASUVORK5CYII='), c => c.charCodeAt(0))
    const data = new DataTransfer(); data.items.add(new File([bytes],'clipboard.png',{type:'image/png'}))
    // Firefox discards constructor-supplied clipboardData on synthetic events.
    const event = new ClipboardEvent('paste',{bubbles:true,cancelable:true})
    Object.defineProperty(event,'clipboardData',{value:data})
    element.dispatchEvent(event)
  })
  await expect(page.getByRole('img',{name:'Pasted image preview'})).toBeVisible()
  await page.getByLabel('Filename',{exact:true}).fill(`image-${suffix}.png`)
  expect((await request.get(`/api/v1/files/download?path=/image-${suffix}.png`)).status()).toBe(404)
  await page.getByRole('button',{name:'Save file',exact:true}).click()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText(`image-${suffix}.png`,{exact:true})).toBeVisible()
  await page.locator('input[type=file]').setInputFiles({name:`upload-a-${suffix}.txt`,mimeType:'text/plain',buffer:Buffer.from('replacement')})
  await page.getByRole('button',{name:/upload conflicts/}).click()
  await page.getByRole('button',{name:'Resolve conflict',exact:true}).click()
  await expect(page.getByRole('heading',{name:'File already exists'})).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Resolve conflict',exact:true})).toBeFocused()
  await page.getByRole('button',{name:'Resolve conflict',exact:true}).click()
  await page.getByRole('button',{name:'Replace',exact:true}).click()
  await expect.poll(async () => (await request.get(`/api/v1/files/download?path=/upload-a-${suffix}.txt`)).text()).toBe('replacement')
  await page.getByRole('button',{name:'Close queue',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:`upload-a-${suffix}.txt`,mimeType:'text/plain',buffer:Buffer.from('must not replace')})
  await page.getByRole('button',{name:/upload conflicts/}).click()
  await page.getByRole('button',{name:'Resolve conflict',exact:true}).click()
  await page.getByRole('button',{name:'Keep existing',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Upload queue',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Resolve conflict',exact:true})).toHaveCount(0)
  expect(await (await request.get(`/api/v1/files/download?path=/upload-a-${suffix}.txt`)).text()).toBe('replacement')
  await page.getByRole('button',{name:'Close queue',exact:true}).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:`test-results/transfers-${suffix}.png`,fullPage:true})
})

test('cancel an active upload and retry from the beginning', async ({ page, request, browserName }, info) => {
  test.skip(browserName !== 'chromium', 'Network upload throttling uses Chromium CDP; cancellation also has backend integration coverage.')
  const name = `cancel-${info.project.name}.bin`
  await page.goto('/')
  await expect(page.getByText('Connected',{exact:true})).toBeVisible()
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Network.enable')
  await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:1024*1024,uploadThroughput:128*1024})
  await page.locator('input[type=file]').setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.alloc(1024*1024,7)})
  await page.getByRole('button',{name:'Open upload queue'}).click()
  await expect.poll(async () => (await (await request.get('/api/v1/transfers')).json() as {path:string;state:string;transferred_bytes:number}[]).some(item => item.path===`/${name}` && item.state==='uploading' && item.transferred_bytes>0)).toBe(true)
  await page.getByRole('button',{name:`Cancel ${name}`,exact:true}).click()
  await expect(page.locator('.queue-item').filter({hasText:name}).locator('.transfer-state')).toHaveText('cancelled')
  expect((await request.get(`/api/v1/files/download?path=/${name}`)).status()).toBe(404)
  await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1})
  await page.getByRole('button',{name:'Retry',exact:true}).click()
  await expect(page.locator('.queue-item').filter({hasText:name}).locator('.transfer-state')).toHaveText('completed')
  expect((await request.get(`/api/v1/files/download?path=/${name}`)).status()).toBe(200)
  await cdp.detach()
})
