import { test, expect } from '@playwright/test'
test('many-file directory remains searchable and responsive', async ({page},info) => {
  await page.goto('/')
  const start = performance.now()
  await page.getByRole('button',{name:'Many files',exact:true}).click()
  await expect(page.getByRole('listitem')).toHaveCount(100)
  const loadMs = Math.round(performance.now()-start)
  const rows = await page.getByRole('listitem').count()
  await page.getByLabel('Select file-000000.txt', {exact:true}).check()
  await page.getByRole('button',{name:'Next page'}).click()
  await expect(page.getByRole('listitem',{name:'file-000100.txt',exact:true})).toBeAttached()
  await page.getByLabel('Select file-000100.txt', {exact:true}).check()
  await expect(page.getByRole('region',{name:'Selected items'})).toContainText('2 selected')
  const search = performance.now()
  await page.getByLabel('Search files').fill('file-009999')
  await expect(page.getByRole('listitem')).toHaveCount(1)
  await expect(page.getByRole('listitem',{name:'file-009999.txt',exact:true})).toBeAttached()
  const searchMs = Math.round(performance.now()-search)
  await page.getByLabel('Search files').fill('')
  await page.getByRole('button',{name:'Grid view',exact:true}).click()
  await expect(page.getByRole('listitem')).toHaveCount(100)
  await expect(page.getByRole('listitem',{name:'file-000000.txt',exact:true})).toBeAttached()
  console.log(JSON.stringify({project:info.project.name,entries:10000,renderedRows:rows,loadMs,searchMs}))
})


test('folders precede files in both views, search and pagination', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button',{name:'Ordering',exact:true}).click()
  const names = () => page.getByRole('listitem').evaluateAll(items => items.map(item => item.getAttribute('aria-label')))
  await expect.poll(async () => (await names()).slice(0,3)).toEqual(['m-folder','z-folder','a-file-000.txt'])
  await page.getByRole('button',{name:'Next page',exact:true}).click()
  await expect.poll(names).toEqual(['a-file-098.txt','a-file-099.txt'])
  await page.getByRole('button',{name:'Previous page',exact:true}).click()
  await page.getByRole('button',{name:'Grid view',exact:true}).click()
  await expect.poll(async () => (await names()).slice(0,3)).toEqual(['m-folder','z-folder','a-file-000.txt'])
  await page.getByLabel('Search files').fill('-f')
  await expect.poll(async () => (await names()).slice(0,3)).toEqual(['m-folder','z-folder','a-file-000.txt'])
  await page.getByRole('button',{name:'Refresh files',exact:true}).click()
  await expect.poll(async () => (await names()).slice(0,3)).toEqual(['m-folder','z-folder','a-file-000.txt'])
})
