import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
test('host changes logging without revoking uploads and views real live diagnostics',async ({page,request},info) => {
  await page.goto('/')
  await page.getByRole('button',{name:'Host settings',exact:true}).click()
  const settings=page.getByRole('dialog',{name:'Host settings',exact:true})
  await settings.getByRole('button',{name:'logging',exact:true}).click()
  await settings.getByLabel('Logging level',{exact:true}).selectOption('debug')
  const hostWrites:string[]=[]
  page.on('request',r=>{if(r.method()==='PUT' && r.url().endsWith('/api/v1/host/settings')) hostWrites.push(r.url())})
  await settings.getByRole('button',{name:'Save changes',exact:true}).click()
  await expect(settings).not.toBeVisible()
  expect(hostWrites).toEqual([])
  expect((await (await request.get('/api/v1/host/logs/config')).json()).level).toBe('debug')
  await page.getByRole('button',{name:'Host settings',exact:true}).click()
  await settings.getByRole('button',{name:'logging',exact:true}).click()
  await expect(settings.getByLabel('Logging level',{exact:true})).toHaveValue('debug')
  await settings.getByRole('button',{name:'Open logs',exact:true}).click()
  const logs=page.getByRole('dialog',{name:'Host logs',exact:true})
  await expect(logs.getByRole('status')).toHaveText('Live updates connected')
  await expect(logs.getByText('Logging level changed',{exact:true}).first()).toBeVisible()
  const id=Buffer.from(info.project.name).toString('hex').padEnd(32,'0'), key='b'.repeat(32)
  const response=await request.post(`/api/v1/uploads?path=/log-${info.project.name}.txt`,{headers:{'Content-Type':'application/octet-stream','X-SplitShare-Request':'1','X-Transfer-ID':id,'X-Transfer-Key':key},data:Buffer.from('log diagnostic')})
  expect(response.status()).toBe(201)
  await expect(logs.getByText('Upload completed',{exact:true}).first()).toBeVisible()
  await expect(logs.getByText('Upload publication started',{exact:true}).first()).toBeVisible()
  await logs.getByRole('searchbox',{name:'Search logs',exact:true}).fill(id)
  await expect(logs.getByText('Upload completed',{exact:true}).first()).toBeVisible()
  await expect(logs.getByText('Logging level changed',{exact:true})).toHaveCount(0)
  expect(await logs.innerText()).not.toContain(key)
  expect(await logs.innerText()).not.toContain(`log-${info.project.name}.txt`)
  await logs.getByRole('combobox',{name:'Log level filter',exact:true}).selectOption('WARN')
  await expect(logs.getByText('No matching logs.',{exact:true})).toBeVisible()
  await logs.getByRole('combobox',{name:'Log level filter',exact:true}).selectOption('all')
  await logs.getByRole('combobox',{name:'Log level filter',exact:true}).focus()
  await page.keyboard.press('Tab')
  await expect(logs.getByRole('list',{name:'Log entries',exact:true})).toBeFocused()
  await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))))
  expect((await new AxeBuilder({page}).include('.logs-dialog').analyze()).violations).toEqual([])
  await page.screenshot({path:`test-results/logs-${info.project.name}.png`})
  await logs.getByRole('button',{name:'Clear logs',exact:true}).click()
  await expect(logs.getByRole('listitem')).toHaveCount(0)
  await logs.getByRole('button',{name:'Close logs',exact:true}).click()
  await expect(settings.getByRole('button',{name:'Open logs',exact:true})).toBeFocused()
  await settings.getByLabel('Logging level',{exact:true}).selectOption('warn')
  await settings.getByRole('button',{name:'Save changes',exact:true}).click()
})

test('log viewer reports load failures and can refresh',async ({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Host settings',exact:true}).click()
  await page.getByRole('button',{name:'logging',exact:true}).click()
  await page.route('**/api/v1/host/logs',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'UNAVAILABLE',message:'Logs unavailable.'}})}))
  await page.getByRole('button',{name:'Open logs',exact:true}).click()
  const logs=page.getByRole('dialog',{name:'Host logs',exact:true})
  await expect(logs.getByRole('alert')).toHaveText('Logs unavailable.')
  await page.unroute('**/api/v1/host/logs')
  await logs.getByRole('button',{name:'Refresh',exact:true}).click()
  await expect(logs.getByRole('alert')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(logs).not.toBeVisible()
})
