import {test,expect} from '@playwright/test'
const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aSuoAAAAASUVORK5CYII='

for (const width of [390,1024]) test(`Upload opens one native picker at width ${width}`, async ({page,request},info) => {
  await page.setViewportSize({width,height:844})
  await page.goto('/')
  const choose = page.waitForEvent('filechooser')
  await page.getByRole('button',{name:'Upload files',exact:true}).click()
  const chooser = await choose
  expect(await chooser.element().getAttribute('accept')).toBeNull()
  expect(chooser.isMultiple()).toBe(true)
  await expect(page.getByRole('dialog',{name:'Upload',exact:true})).toHaveCount(0)
  await chooser.setFiles([{name:'photo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')},{name:'cancel-photo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')}])
  const preview = page.getByRole('dialog',{name:'Upload image',exact:true})
  await expect(preview.getByRole('img',{name:'Image preview'})).toBeVisible()
  const name = `confirmed-${width}-${info.project.name}.png`
  await preview.getByLabel('Filename',{exact:true}).fill(name)
  expect((await request.get(`/api/v1/files/download?path=/${name}`)).status()).toBe(404)
  await preview.getByRole('button',{name:'Upload',exact:true}).click()
  await expect.poll(async () => (await request.get(`/api/v1/files/download?path=/${name}`)).status()).toBe(200)
  expect(await (await request.get(`/api/v1/files/download?path=/${name}`)).body()).toEqual(Buffer.from(png,'base64'))
  await expect(preview.getByLabel('Filename',{exact:true})).toHaveValue('cancel-photo.png')
  await preview.getByRole('button',{name:'Cancel',exact:true}).click()
  expect((await request.get('/api/v1/files/download?path=/cancel-photo.png')).status()).toBe(404)
})

test('touch paste has only the input and images with unsupported previews remain uploadable', async ({page,request},info) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByRole('button',{name:'Paste',exact:true}).click()
  const dialog = page.getByRole('dialog',{name:'Paste from clipboard',exact:true})
  await expect(dialog.getByText('Touch and hold here, then choose Paste.',{exact:true})).toBeVisible()
  await expect(dialog.getByRole('textbox',{name:'Paste area',exact:true})).toBeEditable()
  await expect(dialog.getByRole('button')).toHaveText(['Cancel'])
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click()
  const choose = page.waitForEvent('filechooser')
  await page.getByRole('button',{name:'Upload files',exact:true}).click()
  const name = `original-${info.project.name}.heic`, original = Buffer.from('unsupported image fixture')
  await (await choose).setFiles({name,mimeType:'image/heic',buffer:original})
  const preview = page.getByRole('dialog',{name:'Upload image',exact:true})
  await expect(preview.getByRole('status')).toContainText('cannot be previewed')
  await preview.getByRole('button',{name:'Upload',exact:true}).click()
  await expect.poll(async () => (await request.get(`/api/v1/files/download?path=/${name}`)).status()).toBe(200)
  expect(await (await request.get(`/api/v1/files/download?path=/${name}`)).body()).toEqual(original)
})
