import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function audit(page: Page) {
  // Measure final colors after finite entrance fades, not an intermediate opacity.
  await page.evaluate(() => Promise.all(document.getAnimations()
    .filter(animation => animation.effect?.getTiming().iterations !== Infinity)
    .map(animation => animation.finished.catch(() => {}))))
  const result = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()
  expect(result.violations.map(item => ({id:item.id, nodes:item.nodes.map(node => node.target)}))).toEqual([])
}

test('accessible layout, keyboard menu, dialogs and reduced motion', async ({page},info) => {
  await page.goto('/')
  await expect(page.getByText('Connected',{exact:true})).toBeVisible()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText('hello.txt',{exact:true})).toBeVisible()
  await expect(page.locator('.topbar').getByRole('button',{name:'Share with QR',exact:true})).toHaveCount(1)
  await expect(page.getByRole('region',{name:'File controls'}).getByRole('button',{name:'Host settings'})).toHaveCount(0)
  await audit(page)
  await page.getByRole('button',{name:'Grid view',exact:true}).click()
  await audit(page)
  await page.screenshot({path:`test-results/production-grid-${info.project.name}.png`})
  await page.getByRole('button',{name:'List view',exact:true}).click()
  const item = page.getByRole('listitem',{name:'hello.txt',exact:true})
  await item.focus(); await page.keyboard.press('Shift+F10')
  const menu = page.getByRole('dialog',{name:'Item actions',exact:true})
  await expect(menu).toBeVisible()
  await expect(menu.getByRole('menuitem',{name:'Download',exact:true})).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitem',{name:'Rename',exact:true})).toBeFocused()
  await audit(page)
  const bounds = await menu.boundingBox(), viewport = page.viewportSize()!
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(viewport.width)
  expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(viewport.height)
  await page.screenshot({path:`test-results/actions-${info.project.name}.png`})
  await page.keyboard.press('Escape'); await expect(item).toBeFocused()
  const create = page.getByRole('button',{name:'Create folder',exact:true})
  await create.click()
  const dialog = page.getByRole('dialog',{name:'Create folder',exact:true})
  await expect(dialog.getByLabel('Name',{exact:true})).toBeFocused()
  await audit(page)
  await page.keyboard.press('Shift+Tab')
  expect(await dialog.evaluate(dialog => dialog.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape'); await expect(create).toBeFocused()
  await page.emulateMedia({reducedMotion:'reduce'})
  await create.click()
  expect(await dialog.evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  expect(await dialog.evaluate(element => getComputedStyle(element,'::backdrop').animationName)).toBe('none')
  expect(await dialog.evaluate(element => getComputedStyle(element,'::backdrop').backdropFilter)).toContain('blur(10px)')
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Host settings',exact:true}).click()
  await expect(page.getByRole('checkbox',{name:'Browse',exact:true})).toBeVisible()
  await audit(page)
  await page.screenshot({path:`test-results/settings-${info.project.name}.png`})
  await page.keyboard.press('Escape')
  expect(await page.locator('body').innerText()).not.toMatch(/\/home\/|\/tmp\/|[A-Z]:\\Users\\|splitshare-e2e-/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('selection, real downloads and confirmed bulk deletion', async ({page,request},info) => {
  const folders = [`Selected-a-${info.project.name}`,`Selected-b-${info.project.name}`]
  for (const name of folders) expect((await request.post('/api/v1/directories',{headers:{'X-SplitShare-Request':'1'},data:{parent:'/',name}})).status()).toBe(201)
  await page.goto('/')
  await expect(page.getByRole('checkbox',{name:`Select ${folders[0]}`,exact:true})).toBeVisible()
  for (const name of folders) await page.getByRole('checkbox',{name:`Select ${name}`,exact:true}).check()
  await page.getByRole('button',{name:'Delete selected',exact:true}).click()
  await page.getByLabel('Confirm deletion').fill('DELETE')
  await page.getByRole('button',{name:'Delete',exact:true}).click()
  for (const name of folders) await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0)
  await page.getByRole('checkbox',{name:'Select hello.txt',exact:true}).check()
  await page.getByRole('button',{name:'Download selected',exact:true}).click()
  const download = page.waitForEvent('download')
  await page.getByRole('dialog',{name:'Selected downloads'}).getByRole('link',{name:'hello.txt',exact:true}).click()
  expect((await download).suggestedFilename()).toBe('hello.txt')
  await page.getByRole('button',{name:'Done',exact:true}).click()
  await page.getByRole('button',{name:'Clear selection',exact:true}).click()
  await page.getByLabel('Search files').fill('definitely-absent-name')
  await expect(page.getByRole('heading',{name:'No matching files'})).toBeVisible()
  await page.getByRole('button',{name:'Clear search',exact:true}).first().click()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText('hello.txt',{exact:true})).toBeVisible()
})

test('initial failure and network reconnect converge to real server state', async ({page,context,request},info) => {
  await page.route('**/api/**',route => route.abort('connectionfailed'))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Host unavailable'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Refresh files'})).toBeEnabled()
  await page.unroute('**/api/**')
  await page.getByRole('button',{name:'Refresh files'}).click()
  await expect(page.getByRole('region',{name:'Files',exact:true}).getByText('hello.txt',{exact:true})).toBeVisible()
  await expect(page.getByText('Connected',{exact:true})).toBeVisible()
  await context.setOffline(true)
  await expect(page.getByText('Offline',{exact:true})).toBeVisible({timeout:15000})
  const name = `Reconnect-${info.project.name}`
  expect((await request.post('/api/v1/directories',{headers:{'X-SplitShare-Request':'1'},data:{parent:'/',name}})).status()).toBe(201)
  await context.setOffline(false)
  await expect(page.getByRole('button',{name,exact:true})).toBeVisible({timeout:15000})
  await expect(page.getByText('Connected',{exact:true})).toBeVisible()
})

test('a lost upload response remains unconfirmed until server reconciliation', async ({page,request},info) => {
  await page.goto('/')
  await expect(page.getByText('Connected',{exact:true})).toBeVisible()
  const name = `uncertain-${info.project.name}.txt`
  const content = Buffer.from('published despite lost response')
  // Suppress just this attempt's live events to exercise the ambiguous response path.
  await page.context().setOffline(true)
  await expect(page.getByText('Offline',{exact:true})).toBeVisible()
  await page.route('**/api/v1/events',route => route.abort())
  await page.route('**/api/v1/transfers',route => route.abort())
  await page.context().setOffline(false)
  await page.route('**/api/v1/uploads?**',async route => {
    // WebKit interception omits File bodies; forward the exact fixture bytes.
    const response = await route.fetch({postData:content})
    expect(response.status()).toBe(201)
    await route.abort('connectionfailed')
  })
  await page.locator('input[type=file]').setInputFiles({name,mimeType:'text/plain',buffer:content})
  await page.getByRole('button',{name:'Open upload queue'}).click()
  const row = page.locator('.queue-item').filter({hasText:name})
  await expect(row.locator('.transfer-state')).toHaveText('unconfirmed')
  expect(await (await request.get(`/api/v1/files/download?path=/${name}`)).text()).toBe('published despite lost response')
  await page.unroute('**/api/v1/transfers')
  await row.getByRole('button',{name:'Check status'}).click()
  await expect(row.locator('.transfer-state')).toHaveText('completed')
})
