import { test, expect } from '@playwright/test'
import jsQR from 'jsqr'

test('host settings, local QR, join cookie and token rotation', async ({ page, request }, info) => {
  const initial = await (await request.get('/api/v1/host/settings')).json()
  const external: string[] = []
  page.on('request', outgoing => { if (!outgoing.url().startsWith('http://127.0.0.1:43123')) external.push(outgoing.url()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'Host settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Host settings' })
  await settings.getByRole('checkbox', { name: 'Delete', exact: true }).check()
  await settings.getByRole('button', { name: 'transfers', exact: true }).click()
  await settings.getByLabel('Allow parallel uploads').uncheck()
  await settings.getByRole('button', { name: 'Save changes' }).click()
  await expect(settings).not.toBeVisible()
  let saved = await (await request.get('/api/v1/host/settings')).json()
  expect(saved.permissions.delete).toBe(true)
  expect(saved.parallel_uploads_enabled).toBe(false)
  expect((await (await request.get('/api/v1/status')).json()).upload_concurrency).toBe(1)
  await page.getByRole('button', { name: 'Share with QR', exact: true }).click()
  const sharing = page.getByRole('dialog', { name: 'Share with QR' })
  const addresses = sharing.getByLabel('Network address', { exact: true })
  const options = await addresses.locator('option').evaluateAll(options => options.map(option => (option as HTMLOptionElement).value))
  expect(options.length).toBeGreaterThan(0)
  for (const url of options) {
    await addresses.selectOption(url)
    await expect(sharing.getByLabel('Share link', { exact: true })).toHaveValue(url)
  }
  await addresses.selectOption(options.find(url => url.startsWith('http://127.0.0.1:'))!)
  const oldUrl = await sharing.getByLabel('Share link', { exact: true }).inputValue()
  expect(oldUrl).toMatch(/^http:\/\/127\.0\.0\.1:43123\/j\/[a-f0-9]{64}$/)
  await expect(sharing.getByText('This address works only on this host.', { exact: false })).toBeVisible()
  const pixels = await sharing.locator('canvas').evaluate((canvas: HTMLCanvasElement) => {
    const data = canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height)
    return { data: Array.from(data.data), width: data.width, height: data.height }
  })
  expect(jsQR(new Uint8ClampedArray(pixels.data), pixels.width, pixels.height)?.data).toBe(oldUrl)
  expect(external).toEqual([])
  await page.screenshot({ path: `test-results/sharing-${info.project.name}.png` })
  await sharing.getByRole('button', { name: 'Done', exact: true }).click()
  const joined = await request.get(oldUrl, { maxRedirects: 0 })
  expect(joined.status()).toBe(303)
  expect(joined.headers()['set-cookie']).toContain('HttpOnly; SameSite=Strict; Path=/')
  await page.goto(oldUrl)
  await expect(page).toHaveURL('/')
  const session = (await page.context().cookies()).find(cookie => cookie.name === 'splitshare_session')!
  expect(session.httpOnly).toBe(true)
  expect(session.sameSite).toBe('Strict')
  expect(await page.evaluate(() => document.cookie)).not.toContain('splitshare_session')
  await page.getByRole('button', { name: 'Host settings', exact: true }).click()
  await settings.getByRole('button', { name: 'security', exact: true }).click()
  await settings.getByRole('button', { name: 'Rotate share token' }).click()
  await expect(settings.getByRole('status')).toContainText('Previous links and remote sessions are revoked')
  expect((await request.get(oldUrl, { maxRedirects: 0 })).status()).toBe(401)
  await settings.getByLabel('Access mode').selectOption('open_lan')
  await expect(settings.getByText('Any reachable client can connect.', { exact: false })).toBeVisible()
  await settings.getByRole('button', { name: 'Save changes' }).click()
  await expect(settings).not.toBeVisible()
  saved = await (await request.get('/api/v1/host/settings')).json()
  expect(saved.share_mode).toBe('open_lan')
  await request.put('/api/v1/host/settings', { headers: { 'X-SplitShare-Request': '1' }, data: initial })
})
